Dodanie elementów dynamicznych do strony. Strona główna zakładki o na…
infoshareacademy/jfdz6-the-others pull request #13
Opened 2017-09-06 10:27 UTC by piotrbarcik

Dodanie elementów dynamicznych do strony. Strona główna zakładki o nas, kontakt, informacje o komunikacji. Czekam na recenzję.

2017-09-06 12:50 UTC, MarcinFort commented on index.html
> +          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
Wszystkie zewnętrzene stylesheety lepiej załączać ponad naszym prywatnym, żeby nam nic nie ponadpisywały - raz już tak popsuliśmy menu ;) Warto zmienić nawet jeśli w tym wypadku nie ma problemu.

2017-09-06 13:12 UTC, MarcinFortuna requested changes
Wolałbym żeby elementy ruchome się ruszały tylko raz, po załadowaniu strony lub też po zmianie sekcji, a nie że social media i "Twój przewodnik..." ciągle tańczą :/ To jest irytujące dla użytkownika. Pozostałe elementy ok.

2017-09-06 16:49 UTC, KajaSzarafinska commented on index.html
> +    <div class="menu-nav-bar animated shake">
w menu raczej bym nie dawała żadnej animacji

2017-09-06 16:50 UTC, KajaSzarafinska commented on index.html
> +            <div class="socialmedia animated infinite tada">
j.w.

2017-09-06 16:50 UTC, KajaSzarafinska commented on index.html
> +    <div class="scroll-bg animated slideInUp"></div>
j.w.

2017-09-06 16:51 UTC, KajaSzarafinska commented on index.html
> +        <div class="divzajawka animated rotateInDownLeft"><i class="fa fa-connectdevelop fa-5x"></i></div>
to jest fajne, tak samo zrobiłabym opis do zajawki

2017-09-06 16:51 UTC, KajaSzarafinska commented on index.html
> +                    <div class="form-area animated bounceInLeft">
myślę, że można usunąć

2017-09-06 16:51 UTC, KajaSzarafinska commented on index.html
> +    <div class="container animated wobble">
bez animacji, hovery są i starczy

2017-09-06 16:52 UTC, KajaSzarafinska commented on index.html
> +    <div class="info container animated fadeInDown">
to jest fajne i delikatne. git :) :+1:

2017-09-06 16:53 UTC, KajaSzarafinska requested changes
za dużo się dzieje. ja bym zrobiła tylko jedną animację, że nasza zajawka wjeżdża + ewentualnie można zostawić animacje na sekcji info.

2017-09-06 23:19 UTC, norbertbrzeski commented on index.html
> +    <div class="menu-nav-bar animated shake">
Postarajcie sie nie grzebac w menu.Ja sie nim zajme :-)

2017-09-06 23:23 UTC, norbertbrzeski requested changes
Tak jak we wczesniejszych komentarzach. Commit Do poprawy :-1:

2017-09-07 09:18 UTC, piotrbarcik commented
Naniesione poprawki po uwagach grupy.

2017-09-07 09:19 UTC, piotrbarcik commented
Można sprawdzić jeszcze raz czy może być.

2017-09-07 17:02 UTC, KajaSzarafinska approved these changes

2017-09-07 21:09 UTC, MarcinFortuna approved these changes

2017-09-07 21:24 UTC, norbertbrzeski commented
Teraz jest okej :+1:

2017-09-07 21:24 UTC, norbertbrzeski approved these changes

2017-09-08 07:15 UTC, merged