Add new menu
infoshareacademy/jfdz6-the-others pull request #16
Opened 2017-09-09 15:30 UTC by norbertbrzeski

2017-09-10 15:22 UTC, KajaSzarafinska requested changes
Menu działa poprawnie, ale wymaga ostylowania, żeby wyglądało tak jak poprzednio. Czarne, z hoverem, na 100% szerokości ekranu.

2017-09-10 20:48 UTC, MarcinFortuna requested changes
Poza inline comments, sądzę, że hamburger pojawia się trochę za wcześnie i jest za mały w stosunku do całości - nie będzie wyglądało dobrze na telefonach.

2017-09-10 20:48 UTC, MarcinFort commented on index.html
> +
Czemu zostawiasz tyle wolnych linijek? Dziwnie to wygląda w git diff i sprawia wrażenie, jakbyś dodał znacznie poważniejsze zmiany niż dodałeś naprawdę.

2017-09-10 20:48 UTC, MarcinFort commented on index.html
> +    <!--&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;-->
Jaki jest cel tej linijki?

2017-09-13 14:26 UTC, norbertbrzeski commented
Poprawki Menu
-Stawiony pseudo element hover
-Menu ustawione na 100% szerokosci
-Hamburger pojawiajacy sie pozniej ( z 768px na 425px)
-Powiekszona ikona hamburgera
-Usuniecie zbednych komentarzy
-Pozbycie sie pustych linijek

2017-09-13 17:40 UTC, MarcinFortuna requested changes
Sam hamburger wygląda fajnie, ale wydaje mi się, że możnaby inaczej rozplanować zmniejszanie się przycisków. Na laptopie na pełnej rozdzielczości przyciski menu są za duże, za bardzo się rzucają w oczy i są między nimi za małe odległości (zlewają się wizualnie). Mi się de facto bardzo podobało poprzednie menu, było rozmiarowo w sam raz, tyle tylko, że się nie zmniejszało odpowiednio. Więc przy pełnej rozdzielczości może warto wrócić do tamtych ustawień? A i hamburger powinien się pojawiać wcześniej: patrzę właśnie przy szerokości 410 i tu z kolei przyciski menu są bardzo małe... (tak, wiem, że poprzednio prosiłem o coś odwrotnego - może da się wypośrodkować? ;) Kolejna uwaga: warto popracować nad likwidacją białego paska pomiędzy menu a poszczególnymi sekcjami.

2017-09-15 16:16 UTC, KajaSzarafinska commented
Ja też podtrzymuję uwagi Marcina :( dużo lepiej, ale to ciągle nie jest to menu, które mieliśmy. Czy nie dałoby rady zrobić po prostu responsywności na tym starym? poza tym teraz bardzo widoczny jest ten czarny pasek w momencie hovera

2017-09-15 19:04 UTC, closed without merging